import LenisSmoothScroll from '@/utils/LenisSmoothScroll'
import './globals.css'
import type { Metadata } from 'next'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

// Example Metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}: {children: React.ReactNode}) {

  return (
    <html lang="en">
      <body>
        <Nav />
        <main>
          {children}
        </main>
        <Footer />
        <LenisSmoothScroll />
      </body>
    </html>
  )
}
